name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Hello World Docker image
#.    run: docker build . --file Dockerfile --tag hellocontainer:$(date +%s)
      run: docker build . --file Dockerfile --tag tkoclass1/hellocontainer:v2
      
    - name: Download Scanner
      run: / 
           curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
#   - name: Grant Exec Permission
           chmod +x ./sysdig-cli-scanner
#   - name: Scan image
           SECURE_API_TOKEN=5288f6c4-2e4e-4be9-8e98-f62ab548a233 ./sysdig-cli-scanner --apiurl https://us2.app.sysdig.com tkoclass1/hellocontainer:v2
